apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  type: LoadBalancer
#  type: NodePort
  ports:
    - name: "8031"
      port: 8031
      targetPort: 3000
  selector:
    io.kompose.service: grafana
# status:
#   loadBalancer: {}
