apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeexp
  name: nodeexp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodeexp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.service: nodeexp
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($|/)
          image: prom/node-exporter
          name: nodeexp
          ports:
            - containerPort: 9100
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/proc
              name: nodeexp-hostpath0
              readOnly: true
            - mountPath: /host/sys
              name: nodeexp-hostpath1
              readOnly: true
            - mountPath: /rootfs
              name: nodeexp-hostpath2
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /proc
          name: nodeexp-hostpath0
        - hostPath:
            path: /sys
          name: nodeexp-hostpath1
        - hostPath:
            path: /
          name: nodeexp-hostpath2
status: {}
