apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ping
  name: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ping
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.service: ping
    spec:
      containers:
        - args:
            - --config.file=/config/blackbox.yml
          image: prom/blackbox-exporter
          name: ping
          ports:
            - containerPort: 9115
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: ping-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: {{ required "pwd is required, use --set pwd=`pwd` in command line" .Values.pwd }}/blackbox/config
          name: ping-hostpath0
status: {}
