apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ping
  name: ping
spec:
  ports:
    - name: "9115"
      port: 9115
      targetPort: 9115
  selector:
    io.kompose.service: ping
status:
  loadBalancer: {}
