apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: ping-volume0
  name: ping-volume0
spec:
  storageClassName: ping-volume0
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ required "pwd is required, use --set pwd=`pwd` in command line" .Values.pwd }}/blackbox"
status: {}
