apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sonos
  name: sonos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonos
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: sonos
    spec:
      containers:
        - args:
            - --address=0.0.0.0:1915
          image: maxandersen/sonos_exporter
          name: sonos
          ports:
            - containerPort: 1915
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
