apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: speedtest
  name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: speedtest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c --volumes hostPath
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.service: speedtest
    spec:
      containers:
        - image: stefanwalther/speedtest-exporter
          name: speedtest
          ports:
            - containerPort: 9696
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
