apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --volumes hostPath
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: speedtest
  name: speedtest
spec:
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
  selector:
    io.kompose.service: speedtest
status:
  loadBalancer: {}
